name: Build, PR & Release Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_retype_site:
    name: Publish Retype powered website to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the workflow has permissions to push to the repository

    steps:
      - uses: actions/checkout@v4  # Checkout the repository

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x  # Use the appropriate .NET version if required by Retype

      - uses: retypeapp/action-build@latest  # Build the Retype site

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true  # Push the built site to the `retype` branch

  build_electron_app:
    name: Build and Package Electron App
    runs-on: ubuntu-latest
    needs: build_retype_site  # This ensures the Retype build happens before the Electron build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you're using

      - name: Install dependencies
        run: npm install

      - name: Build the Electron app
        run: npm run build  # Assuming you have a build script for Electron
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass the GH_TOKEN from secrets to npm run build

      - name: Package the Electron app
        run: npm run package  # Assuming you have a packaging script

      - name: Create a new branch for Electron build artifacts
        run: |
          git checkout -b build-artifacts
          git add path/to/build/artifacts/*  # Adjust to where your packaged Electron app is
          git commit -m "Add Electron build artifacts"
          git push origin build-artifacts

      - name: Create a Pull Request for the Electron build
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "New Electron Build"
          body: "This PR contains the newly built Electron app."
          base: main
          head: build-artifacts  # Pull request from the `build-artifacts` branch

  release:
    name: Publish Electron Release
    runs-on: ubuntu-latest
    needs: build_electron_app
    if: github.event.pull_request.merged == true  # Trigger only if the PR is merged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Release Electron app
        run: |
          npm run release  # Use electron-builder or another release process for your app

      - name: Publish Release
        uses: ghp-import/ghp-import@v0.6.1
        with:
          source_dir: ./path/to/your/output/directory  # Adjust this to point to your packaged files
          branch: gh-pages
          commit_message: "Release new version"
